# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import os

from PyQt5 import QtCore, QtGui, QtWidgets

def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 604)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_superior = QtWidgets.QFrame(self.frame)
        self.frame_superior.setMinimumSize(QtCore.QSize(0, 42))
        self.frame_superior.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_superior.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(0,0,0);\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: #000000ff;\n"
"border-radius: 20px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(53, 53, 79);\n"
"border-radius: 20px;\n"
"}")
        self.frame_superior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_superior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_superior.setObjectName("frame_superior")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_superior)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame_superior)
        self.label.setStyleSheet("font: 87 12pt \"Arial Black\";\n"
"color: rgb(20,200,220);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(366, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bt_mini = QtWidgets.QPushButton(self.frame_superior)
        self.bt_mini.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_mini.setStyleSheet("")
        self.bt_mini.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("Imagenes/mini.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_mini.setIcon(icon)
        self.bt_mini.setIconSize(QtCore.QSize(38, 38))
        self.bt_mini.setObjectName("bt_mini")
        self.horizontalLayout.addWidget(self.bt_mini)
        self.bt_minimizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_minimizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_minimizar.setStyleSheet("")
        self.bt_minimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(resource_path("Imagenes/minimizar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_minimizar.setIcon(icon1)
        self.bt_minimizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_minimizar.setObjectName("bt_minimizar")
        self.horizontalLayout.addWidget(self.bt_minimizar)
        self.bt_maximizar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_maximizar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_maximizar.setStyleSheet("")
        self.bt_maximizar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(resource_path("Imagenes/maximizar.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_maximizar.setIcon(icon2)
        self.bt_maximizar.setIconSize(QtCore.QSize(38, 38))
        self.bt_maximizar.setObjectName("bt_maximizar")
        self.horizontalLayout.addWidget(self.bt_maximizar)
        self.bt_cerrar = QtWidgets.QPushButton(self.frame_superior)
        self.bt_cerrar.setMinimumSize(QtCore.QSize(40, 40))
        self.bt_cerrar.setStyleSheet("")
        self.bt_cerrar.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(resource_path("Imagenes/x.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_cerrar.setIcon(icon3)
        self.bt_cerrar.setIconSize(QtCore.QSize(38, 38))
        self.bt_cerrar.setObjectName("bt_cerrar")
        self.horizontalLayout.addWidget(self.bt_cerrar)
        self.verticalLayout_2.addWidget(self.frame_superior)
        self.frame_inferior = QtWidgets.QFrame(self.frame)
        self.frame_inferior.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_inferior.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_inferior.setObjectName("frame_inferior")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_inferior)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_inferior)
        self.frame_2.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(53,53,79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20,200,220);\n"
"border-radius: 5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, 9, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bt_1 = QtWidgets.QPushButton(self.frame_2)
        self.bt_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(resource_path("Imagenes/homelogo1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_1.setIcon(icon4)
        self.bt_1.setIconSize(QtCore.QSize(32, 32))
        self.bt_1.setObjectName("bt_1")
        self.verticalLayout_4.addWidget(self.bt_1)
        self.bt_2 = QtWidgets.QPushButton(self.frame_2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(resource_path("Imagenes/vodlogo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_2.setIcon(icon5)
        self.bt_2.setIconSize(QtCore.QSize(32, 32))
        self.bt_2.setObjectName("bt_2")
        self.verticalLayout_4.addWidget(self.bt_2)
        self.bt_3 = QtWidgets.QPushButton(self.frame_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(resource_path("Imagenes/quienesomoslogo2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_3.setIcon(icon6)
        self.bt_3.setIconSize(QtCore.QSize(32, 32))
        self.bt_3.setObjectName("bt_3")
        self.verticalLayout_4.addWidget(self.bt_3)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.frame_4 = QtWidgets.QFrame(self.frame_inferior)
        self.frame_4.setStyleSheet("\n"
"QFrame{\n"
"background-color: rgb(53,53,79)\n"
"}\n"
"\n"
"QLabel{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20,200,220);\n"
"border: 0px solid #14C8DC;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_6.setContentsMargins(-1, -1, 9, 9)
        self.verticalLayout_6.setSpacing(6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_4)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.page_1)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_5.setStyleSheet("QFrame{\n"
"background-color: transparent;\n"
"}\n"
"\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20,200,220);\n"
"border-radius: 5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bt_menu_iz = QtWidgets.QPushButton(self.frame_8)
        self.bt_menu_iz.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(resource_path("Imagenes/izquierda.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_iz.setIcon(icon7)
        self.bt_menu_iz.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_iz.setObjectName("bt_menu_iz")
        self.horizontalLayout_4.addWidget(self.bt_menu_iz)
        self.bt_menu_dr = QtWidgets.QPushButton(self.frame_8)
        self.bt_menu_dr.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(resource_path("Imagenes/derecha.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_menu_dr.setIcon(icon8)
        self.bt_menu_dr.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_dr.setObjectName("bt_menu_dr")
        self.horizontalLayout_4.addWidget(self.bt_menu_dr)
        self.lineEdit = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"border: 2px solid #14c8dc;\n"
"border-radius: 8px;\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(0,0,0);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.bt_busqueda = QtWidgets.QPushButton(self.frame_8)
        self.bt_busqueda.setStyleSheet("border: 0px solid #14C8DC;")
        self.bt_busqueda.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(resource_path("Imagenes/busqueda.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_busqueda.setIcon(icon9)
        self.bt_busqueda.setIconSize(QtCore.QSize(32, 32))
        self.bt_busqueda.setObjectName("bt_busqueda")
        self.horizontalLayout_4.addWidget(self.bt_busqueda)
        self.verticalLayout_16.addWidget(self.frame_8)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label_2.setStyleSheet("background: transparent;")
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.frame_17 = QtWidgets.QFrame(self.frame_5)
        self.frame_17.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 16000000))
        self.frame_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bt_separar = QtWidgets.QPushButton(self.frame_18)
        self.bt_separar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bt_separar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.bt_separar.setObjectName("bt_separar")
        self.horizontalLayout_8.addWidget(self.bt_separar)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setLineWidth(1)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.frame_21 = QtWidgets.QFrame(self.frame_19)
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem2)
        self.statusLabel = QtWidgets.QLabel(self.frame_21)
        self.statusLabel.setText("")
        self.statusLabel.setObjectName("statusLabel")
        self.horizontalLayout_12.addWidget(self.statusLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem3)
        self.verticalLayout_19.addWidget(self.frame_21)
        self.progressBar = QtWidgets.QProgressBar(self.frame_19)
        self.progressBar.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 4px solid rgb(176,18,235);\n"
"    border-radius: 3px;\n"
"    text-align: center;\n"
"    height: 20px;\n"
"    background-color: black;\n"
"    color: white;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(20,200,220);\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_19.addWidget(self.progressBar)
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_20)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.progresBarCancelar = QtWidgets.QPushButton(self.frame_20)
        self.progresBarCancelar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.progresBarCancelar.setStyleSheet("color : red")
        self.progresBarCancelar.setObjectName("progresBarCancelar")
        self.horizontalLayout_11.addWidget(self.progresBarCancelar)
        self.progresBarAceptar = QtWidgets.QPushButton(self.frame_20)
        self.progresBarAceptar.setMaximumSize(QtCore.QSize(250, 16777215))
        self.progresBarAceptar.setBaseSize(QtCore.QSize(0, 0))
        self.progresBarAceptar.setStyleSheet("color: green;")
        self.progresBarAceptar.setObjectName("progresBarAceptar")
        self.horizontalLayout_11.addWidget(self.progresBarAceptar)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_19.addWidget(self.frame_20)
        self.verticalLayout_17.addWidget(self.frame_19)
        self.verticalLayout_16.addWidget(self.frame_17)
        self.verticalLayout_7.addWidget(self.frame_5)
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.page_2)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 300))
        self.frame_7.setStyleSheet("background: transparent;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.frame_6 = QtWidgets.QFrame(self.frame_7)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setStyleSheet("background: transparent;\n"
"QFrame{\n"
"background-color: rgb(53,53,79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20,200,220);\n"
"border-radius: 5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.bt_menu_iz_2 = QtWidgets.QPushButton(self.frame_6)
        self.bt_menu_iz_2.setText("")
        self.bt_menu_iz_2.setIcon(icon7)
        self.bt_menu_iz_2.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_iz_2.setObjectName("bt_menu_iz_2")
        self.horizontalLayout_9.addWidget(self.bt_menu_iz_2)
        self.bt_menu_dr_2 = QtWidgets.QPushButton(self.frame_6)
        self.bt_menu_dr_2.setText("")
        self.bt_menu_dr_2.setIcon(icon8)
        self.bt_menu_dr_2.setIconSize(QtCore.QSize(32, 32))
        self.bt_menu_dr_2.setObjectName("bt_menu_dr_2")
        self.horizontalLayout_9.addWidget(self.bt_menu_dr_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit{\n"
"border: 2px solid #14c8dc;\n"
"border-radius: 8px;\n"
"color: rgb(255,255,255);\n"
"background-color: rgb(0,0,0);\n"
"font: 75 12pt \"Times New Roman\";\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_9.addWidget(self.lineEdit_2)
        self.bt_busqueda_2 = QtWidgets.QPushButton(self.frame_6)
        self.bt_busqueda_2.setStyleSheet("border: 0px solid #14C8DC;")
        self.bt_busqueda_2.setText("")
        self.bt_busqueda_2.setIcon(icon9)
        self.bt_busqueda_2.setIconSize(QtCore.QSize(32, 32))
        self.bt_busqueda_2.setObjectName("bt_busqueda_2")
        self.horizontalLayout_9.addWidget(self.bt_busqueda_2)
        self.verticalLayout_10.addWidget(self.frame_6)
        self.toolBox = QtWidgets.QToolBox(self.frame_7)
        self.toolBox.setStyleSheet("\n"
"QToolBox::tab {\n"
"    background-color: rgb(255,255,255);\n"
"    border-radius: 5px;\n"
"    color: rgb(0,0,0);\n"
"    font: 75 8pt \"MS Shell Dig 2\";\n"
"}\n"
"\n"
"QToolBox::tab:selected {\n"
"    background-color: rgb(20,200,220);\n"
"    font: 75 12pt \"MS Shell Dig 2\";\n"
"    color: rgb(0,0,0);\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.Pagina1 = QtWidgets.QWidget()
        self.Pagina1.setGeometry(QtCore.QRect(0, 0, 527, 164))
        self.Pagina1.setObjectName("Pagina1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Pagina1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_11 = QtWidgets.QFrame(self.Pagina1)
        self.frame_11.setMaximumSize(QtCore.QSize(110, 16777215))
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_Volumen = QtWidgets.QLabel(self.frame_11)
        self.label_Volumen.setStyleSheet("")
        self.label_Volumen.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Volumen.setObjectName("label_Volumen")
        self.verticalLayout_11.addWidget(self.label_Volumen)
        self.horizontalLayout_6.addWidget(self.frame_11)
        self.frame_10 = QtWidgets.QFrame(self.Pagina1)
        self.frame_10.setStyleSheet("background: transparent;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.bass_slider = QtWidgets.QSlider(self.frame_14)
        self.bass_slider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 1px solid rgb(176,18,235);\n"
"    width: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(20,200,220);\n"
"    margin: 1px; /* Centramos el surco en el control */\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: rgb(20,200,220);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    margin: 0 -12px; /* Ajustamos el margen para que se centre correctamente */\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}")
        self.bass_slider.setMaximum(100)
        self.bass_slider.setSingleStep(10)
        self.bass_slider.setProperty("value", 100)
        self.bass_slider.setOrientation(QtCore.Qt.Vertical)
        self.bass_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.bass_slider.setTickInterval(4)
        self.bass_slider.setObjectName("bass_slider")
        self.horizontalLayout_7.addWidget(self.bass_slider)
        self.drum_slider = QtWidgets.QSlider(self.frame_14)
        self.drum_slider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 1px solid rgb(176,18,235);\n"
"    width: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(20,200,220);\n"
"    margin: 1px; /* Centramos el surco en el control */\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: rgb(20,200,220);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    margin: 0 -12px; /* Ajustamos el margen para que se centre correctamente */\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}")
        self.drum_slider.setMaximum(100)
        self.drum_slider.setSingleStep(10)
        self.drum_slider.setProperty("value", 100)
        self.drum_slider.setOrientation(QtCore.Qt.Vertical)
        self.drum_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.drum_slider.setTickInterval(4)
        self.drum_slider.setObjectName("drum_slider")
        self.horizontalLayout_7.addWidget(self.drum_slider)
        self.other_slider = QtWidgets.QSlider(self.frame_14)
        self.other_slider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 1px solid rgb(176,18,235);\n"
"    width: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(20,200,220);\n"
"    margin: 1px; /* Centramos el surco en el control */\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: rgb(20,200,220);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    margin: 0 -12px; /* Ajustamos el margen para que se centre correctamente */\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}")
        self.other_slider.setMaximum(100)
        self.other_slider.setSingleStep(10)
        self.other_slider.setProperty("value", 100)
        self.other_slider.setOrientation(QtCore.Qt.Vertical)
        self.other_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.other_slider.setTickInterval(4)
        self.other_slider.setObjectName("other_slider")
        self.horizontalLayout_7.addWidget(self.other_slider)
        self.vocals_slider = QtWidgets.QSlider(self.frame_14)
        self.vocals_slider.setStyleSheet("QSlider::groove:vertical {\n"
"    border: 1px solid rgb(176,18,235);\n"
"    width: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(20,200,220);\n"
"    margin: 1px; /* Centramos el surco en el control */\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"    background: rgb(20,200,220);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"    margin: 0 -12px; /* Ajustamos el margen para que se centre correctamente */\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:vertical {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}")
        self.vocals_slider.setMaximum(100)
        self.vocals_slider.setSingleStep(10)
        self.vocals_slider.setProperty("value", 100)
        self.vocals_slider.setOrientation(QtCore.Qt.Vertical)
        self.vocals_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.vocals_slider.setTickInterval(4)
        self.vocals_slider.setObjectName("vocals_slider")
        self.horizontalLayout_7.addWidget(self.vocals_slider)
        self.verticalLayout_5.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_10)
        self.frame_15.setStyleSheet("QPushButton{\n"
"background-color: rgb(20,200,220);\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.frame_15)
        self.label_8.setMaximumSize(QtCore.QSize(120, 16777215))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_3.addWidget(self.label_8)
        self.label_7 = QtWidgets.QLabel(self.frame_15)
        self.label_7.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_3.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        self.label_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.label_5 = QtWidgets.QLabel(self.frame_15)
        self.label_5.setMaximumSize(QtCore.QSize(100, 30))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.verticalLayout_5.addWidget(self.frame_15)
        self.horizontalLayout_6.addWidget(self.frame_10)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("Imagenes/paginas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox.addItem(self.Pagina1, icon10, "")
        self.Pagina2 = QtWidgets.QWidget()
        self.Pagina2.setGeometry(QtCore.QRect(0, 0, 527, 164))
        self.Pagina2.setObjectName("Pagina2")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.Pagina2)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_13 = QtWidgets.QFrame(self.Pagina2)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_Pitch = QtWidgets.QLabel(self.frame_13)
        self.label_Pitch.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Pitch.setObjectName("label_Pitch")
        self.verticalLayout_14.addWidget(self.label_Pitch)
        self.verticalLayout_12.addWidget(self.frame_13)
        self.frame_12 = QtWidgets.QFrame(self.Pagina2)
        self.frame_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_12.setStyleSheet("background: transparent;")
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_12)
        self.horizontalSlider.setMaximumSize(QtCore.QSize(50000, 200))
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid rgb(176,18,235);\n"
"    height: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(20,200,220);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(20,200,220);\n"
"    width: 28px;\n"
"    height: 28px;\n"
"left:11px;\n"
"right:11px;\n"
"    margin: -12px; /* Ajustamos el margen para que se centre correctamente */\n"
"    border-radius: 14px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontall {\n"
"    background-color: white;\n"
"    border: 1px solid white;\n"
"}")
        self.horizontalSlider.setMinimum(-8)
        self.horizontalSlider.setMaximum(8)
        self.horizontalSlider.setSingleStep(1)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.horizontalSlider.setTickInterval(2)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_13.addWidget(self.horizontalSlider)
        self.verticalLayout_12.addWidget(self.frame_12)
        self.toolBox.addItem(self.Pagina2, icon10, "")
        self.verticalLayout_10.addWidget(self.toolBox)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.frame_9 = QtWidgets.QFrame(self.page_2)
        self.frame_9.setMaximumSize(QtCore.QSize(3000, 90))
        self.frame_9.setStyleSheet("QFrame{\n"
"background-color: rgb(53,53,79);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 87 12pt \"Arial Black\";\n"
"background-color: #000000ff;\n"
"color: rgb(20,200,220);\n"
"border-radius: 5px;\n"
"border: 1px solid white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: black;\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_15.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_16 = QtWidgets.QFrame(self.frame_9)
        self.frame_16.setStyleSheet("background: transparent;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.barra_tiempo = QtWidgets.QSlider(self.frame_16)
        self.barra_tiempo.setStyleSheet("\n"
"QSlider::groove:horizontal {\n"
"    border: 4px solid rgb(176,18,235);\n"
"    height: 4px; /* Ajustamos el ancho en vez de la altura */\n"
"    background: rgb(176,18,235);\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(20,200,220);\n"
"\n"
"    margin: -4px; /* Ajustamos el margen para que se centre correctamente */\n"
"\n"
"}\n"
"\n"
"QSlider::add-page:horizontall {\n"
"    background-color: black;\n"
"    border: 2px solid rgb(20,200,220);\n"
"    border-radius: 3px;\n"
"}")
        self.barra_tiempo.setOrientation(QtCore.Qt.Horizontal)
        self.barra_tiempo.setObjectName("barra_tiempo")
        self.horizontalLayout_10.addWidget(self.barra_tiempo)
        self.label_3 = QtWidgets.QLabel(self.frame_16)
        self.label_3.setMaximumSize(QtCore.QSize(50, 30))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.verticalLayout_15.addWidget(self.frame_16)
        self.frame_3 = QtWidgets.QFrame(self.frame_9)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bt_rewind = QtWidgets.QPushButton(self.frame_3)
        self.bt_rewind.setText("")
        self.bt_rewind.setIcon(icon7)
        self.bt_rewind.setIconSize(QtCore.QSize(22, 22))
        self.bt_rewind.setObjectName("bt_rewind")
        self.horizontalLayout_5.addWidget(self.bt_rewind)
        self.bt_play = QtWidgets.QPushButton(self.frame_3)
        self.bt_play.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(resource_path("Imagenes/play.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_play.setIcon(icon11)
        self.bt_play.setIconSize(QtCore.QSize(22, 22))
        self.bt_play.setObjectName("bt_play")
        self.horizontalLayout_5.addWidget(self.bt_play)
        self.bt_pausa = QtWidgets.QPushButton(self.frame_3)
        self.bt_pausa.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(resource_path("Imagenes/pausa.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_pausa.setIcon(icon12)
        self.bt_pausa.setIconSize(QtCore.QSize(22, 22))
        self.bt_pausa.setObjectName("bt_pausa")
        self.horizontalLayout_5.addWidget(self.bt_pausa)
        self.bt_stop = QtWidgets.QPushButton(self.frame_3)
        self.bt_stop.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(resource_path("Imagenes/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bt_stop.setIcon(icon13)
        self.bt_stop.setIconSize(QtCore.QSize(22, 22))
        self.bt_stop.setObjectName("bt_stop")
        self.horizontalLayout_5.addWidget(self.bt_stop)
        self.bt_forward = QtWidgets.QPushButton(self.frame_3)
        self.bt_forward.setText("")
        self.bt_forward.setIcon(icon8)
        self.bt_forward.setIconSize(QtCore.QSize(22, 22))
        self.bt_forward.setObjectName("bt_forward")
        self.horizontalLayout_5.addWidget(self.bt_forward)
        self.verticalLayout_15.addWidget(self.frame_3)
        self.verticalLayout_8.addWidget(self.frame_9)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(resource_path("Imagenes/quienesomoslogo2.png")))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_3)
        self.verticalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.verticalLayout_2.addWidget(self.frame_inferior)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Separador Instrumentos"))
        self.bt_1.setText(_translate("MainWindow", "Principal"))
        self.bt_2.setText(_translate("MainWindow", "Reproductor"))
        self.bt_3.setText(_translate("MainWindow", "Quienes somos"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>Selecciona una canción .mp3 o .wav</p><p> para separar las pistas.</p></body></html>"))
        self.bt_separar.setText(_translate("MainWindow", "Separar canción"))
        self.progresBarCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.progresBarAceptar.setText(_translate("MainWindow", "Aceptar"))
        self.label_Volumen.setText(_translate("MainWindow", "VOLUMEN"))
        self.label_8.setText(_translate("MainWindow", "Bass"))
        self.label_7.setText(_translate("MainWindow", "Drums"))
        self.label_6.setText(_translate("MainWindow", "Others"))
        self.label_5.setText(_translate("MainWindow", "Vocal"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Pagina1), _translate("MainWindow", "Page 1"))
        self.label_Pitch.setText(_translate("MainWindow", "PITCH"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Pagina2), _translate("MainWindow", "Page 2"))
        self.label_3.setText(_translate("MainWindow", "00:00"))
